/**
 @brief The file aadd_config.h is generated by CMake from AADDConfig.h.in. 
        CMake replaces the variable names (), where XXX is a string, with varibles set in CMakeLists.txt. 
 */ 

// @brief   The version number of AADD
#define AADD_VERSION_MAJOR 2
#define AADD_VERSION_MINOR 0

// @brief Defining NDEBUG disables assertions, defining DEBUG enables assertions. 
#define DEBUG
